/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("../../../MidcrashStaticCharacter.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.62}>
        <primitive object={nodes.MAIN} />
        <skinnedMesh
          geometry={nodes.SimplePlayerBodyLayer1.geometry}
          material={materials["char.001"]}
          skeleton={nodes.SimplePlayerBodyLayer1.skeleton}
        />
        <skinnedMesh
          geometry={nodes.SimplePlayerBodyLayer2.geometry}
          material={materials["char_alpha.001"]}
          skeleton={nodes.SimplePlayerBodyLayer2.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../MidcrashStaticCharacter.glb");
